services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: api
    environment:
      - POSTGRESQL_CONNECTION_STRING=${POSTGRESQL_CONNECTION_STRING}
      - API_KEY=${API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - invoice_ai_net

  streamlit:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: streamlit
    environment:
      - BASE_URL=${BASE_URL}
      - API_KEY=${API_KEY}
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - invoice_ai_net

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invoice_ai_net

volumes:
  postgres_data:

networks:
  invoice_ai_net:
    external: true