services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: api
    environment:
      - POSTGRESQL_CONNECTION_STRING=postgresql://dev_user:dev_password@db:5444/dev_db
      - API_KEY=${API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      invoice_ai_net:
        ipv4_address: 172.21.0.3

  streamlit:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: streamlit
    environment:
      - BASE_URL=http://api:8080
      - API_KEY=${API_KEY}
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      invoice_ai_net:
        ipv4_address: 172.21.0.2

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      invoice_ai_net:
        ipv4_address: 172.21.0.4

volumes:
  postgres_data:

networks:
  invoice_ai_net:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
