name: Build, Push Docker Images, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Export environment variables
            export POSTGRESQL_CONNECTION_STRING=${{ secrets.POSTGRESQL_CONNECTION_STRING }}
            export API_KEY=${{ secrets.API_KEY }}
            export BASE_URL=${{ secrets.BASE_URL }}
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            
            # Clone the repository
            cd /srv/
            if [ -d "streamlit-invoice-ai" ]; then
              cd streamlit-invoice-ai
              git config --global --add safe.directory /srv/streamlit-invoice-ai
              git pull origin main
            else
              git clone https://github.com/takoai-pl/streamlit-invoice-ai.git
              cd streamlit-invoice-ai
              git config --global --add safe.directory /srv/streamlit-invoice-ai
            fi

            docker-compose up -d